type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']

wheel_separation: 0.45 #0.44
wheel_radius : 0.15
base_frame_id: base_link
odom_frame_id: odom
enable_odom_tf: true
estimate_velocity_from_position: false
cmd_vel_timeout: 0.25

pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]


linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 2.75   # m/s
    #min_velocity           : -0.1   # m/s
    has_acceleration_limits: true
    max_acceleration       : 20.00   # m/s^2
    #min_acceleration       : -0.2  # m/s^2

angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 4.75   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 25.00   # rad/s^2





