diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  front_left_wheel_joint: "front_left_wheel_joint"
  front_right_wheel_joint: "front_right_wheel_joint"
  rear_left_wheel_joint: "rear_left_wheel_joint"
  rear_right_wheel_joint: "rear_right_wheel_joint"
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  wheel_separation: 0.4 # Adjust the value based on your robot's dimensions
  wheel_radius: 0.033 # Adjust the value based on your robot's wheel dimensions
  pid: {p: 1.0, i: 0.0, d: 0.0}