type: joint_state_controller/JointStateController
publish_rate: 50

gazebo_ros_control/pid_gains:
  front_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
  front_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}    
  rear_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
  rear_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
  # left_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}
  # right_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}