type: joint_state_controller/JointStateController
publish_rate: 50

gazebo_ros_control/pid_gains:
  front_left_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
  front_right_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}    
  rear_left_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
  rear_right_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}