joint_state_controller:
type: joint_state_controller/JointStateController
publish_rate: 50
joints:
    - front_left_wheel_joint
    - front_right_wheel_joint
    - rear_left_wheel_joint
    - rear_right_wheel_joint